### ISSUE TITLE
a key disappeared

### ISSUE THREAD

**Issue by nagybal** [StrictLine/MacOSX-KeyboardLayout_WinHUN#1]
Thank You for the layout. I have the 0 next to 1 finally. After restarting the machine however the key between Left-Shift and Y have disappeared and of course it does not give me the "long i" but a 0
![Screenshot 2022-01-06 at 12 52 31](https://user-images.githubusercontent.com/27618042/148450299-2293dfbf-6ed7-4484-818d-2a1d52fad3e2.png)
.

**Comment by nagybal** [comment]
Sorry. I had an US "keyboard" attached.

**Comment by StrictLine** [comment]
Hi / Szia, 
unfortunately, the issue of missing **í** next to the Left-Shift is known, even if I attached a European (German) keyboard. I replaced this key by 0 because of confusion in virtualization or remote apps like Microsoft Remote Desktop or Citrix Workspace.

Even if I update the mappings time to time, whenever I manage to have some time for optimization, I guess, the final and stable solution to get the Hungarian Windows keyboard mapping work is to migrate all the key mappings from Ukele to Karabiner, because Karabiner mappings operate on a lower level, so they work everywhere.

Cheers
